<?php return array (
  'name' => 'P.I.M.S',
  'version' => '1.0.25',
  'full' => '1.0.25',
  'source' => 'git',
  'hash' => 'e5aea0f',
  'tag' => 'v1.0.0',
  'commits_since_tag' => 0,
  'total_commits' => 58,
  'dirty' => true,
  'changed_files' => 2,
  'dirty_fingerprint' => 'c5b4fc8f',
  'dirty_sequence' => 9807,
  'date' => '2026-06-01',
  'meta_label' => '',
);
