<?php return array (
  'name' => 'P.I.M.S',
  'version' => '1.0.32',
  'full' => '1.0.32',
  'source' => 'git',
  'hash' => '00337a1',
  'tag' => NULL,
  'commits_since_tag' => 0,
  'total_commits' => 65,
  'dirty' => true,
  'changed_files' => 2,
  'dirty_fingerprint' => 'edaee0d1',
  'dirty_sequence' => 2550,
  'date' => '2026-06-04',
  'meta_label' => '',
);
